apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uyuni.uyuni.fullname" . }}
  labels:
    {{- include "uyuni.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.uyuni.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "uyuni.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "uyuni.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "uyuni.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.uyuni.container.name }} 
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.uyuni.image.repository }}:{{ .Values.uyuni.image.tag }}"
          command:
          - "/bin/bash"
          - "-c"
          args: ["$CATALINA_HOME/bin/startup.sh && tail -f /dev/null"]
          ports:
          - containerPort: {{ .Values.uyuni.container.containerPort }}
          volumeMounts:
          {{- range $idx, $path := .Values.uyuni.container.mountPaths }}
          - name: uyuni-storage
            mountPath: {{ $path.mountPath }}
            subPath: {{ $path.subPath }} 
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: uyuni-storage
        persistentVolumeClaim:
          claimName: {{ .Values.uyuni.persistentVolumeClaim.name }} 
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}