apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.localStorageClass.name }}
provisioner: {{ .Values.localStorageClass.provisioner }}
volumeBindingMode: {{ .Values.localStorageClass.volumeBindingMode }}
reclaimPolicy: {{ .Values.localStorageClass.reclaimPolicy }}